import type {
  ImageFramingId,
  ImageFramingPreset,
  ImagePerformanceId,
  ImagePerformancePreset,
  ImageSubjectId,
  ImageSubjectPreset,
} from './imageTypes'

/**
 * Biblioteca de presets da categoria "Criar imagem".
 *
 * Fonte única de verdade dos blocos e das compatibilidades de imagem estática.
 * Para adicionar um preset novo, acrescente a entrada no array correspondente.
 *
 * Textos em inglês usam sempre expressões neutras ("the singer from the
 * reference image"), para funcionarem com cantor ou cantora sem duplicar preset.
 */

/** Abertura comum a todos os prompts de imagem. */
export const IMAGE_INTRO =
  'Create a highly realistic professional music performance image using the reference image ' +
  'as the exact visual reference.'

/** Preservação da referência: identidade, roupa, instrumento e cenário. */
export const IMAGE_PRESERVATION =
  'Preserve exactly the identity, face, hair, age, body proportions, clothing, instruments, ' +
  'environment and lighting from the supplied reference image. Keep the same people, the same ' +
  'wardrobe and the same location, without inventing anything that is not in the reference.'

/** Padrão de qualidade fotográfica exigido. */
export const IMAGE_QUALITY =
  'Professional realistic concert photography, believable anatomy, natural posture, realistic ' +
  'hands, coherent instrument proportions, sharp focus and cinematic composition.'

/** Bloco de preparação para lipsync, aplicado só quando há cantor em cena. */
export const IMAGE_LIPSYNC_BLOCK =
  "The singer's face must remain clearly visible and unobstructed, with the mouth fully " +
  'visible and naturally positioned for later lip-sync animation. The face is well lit, in ' +
  'sharp focus, with the head in a natural upright position and the facial features sharp ' +
  'and well defined.'

/** Defeitos recusados em qualquer imagem gerada. */
export const IMAGE_CONSTRAINTS = [
  'no face changes',
  'no identity changes',
  'no clothing changes',
  'no different instruments',
  'no duplicated instruments',
  'no distorted or warped instruments',
  'no extra fingers',
  'no extra limbs',
  'no duplicated people',
  'no additional musicians that are not requested',
  'no incorrect anatomy',
  'no deformed hands',
]

/** Obstruções que inviabilizam o lipsync posterior. */
export const IMAGE_LIPSYNC_CONSTRAINTS = [
  'no microphone blocking the mouth',
  'no hair covering the mouth',
  'no hands covering the face',
  'no harsh shadows over the mouth',
  'no objects in front of the face',
  'no extreme 90-degree profile',
  'no excessively tilted or turned head',
  'no distant framing where the subject is small in frame',
]

export const IMAGE_SUBJECTS: ImageSubjectPreset[] = [
  {
    id: 'singer-solo',
    category: 'image-subject',
    label: 'Cantor sozinho',
    text: 'The singer from the reference image is alone in the frame, performing naturally with authentic posture and a restrained facial expression appropriate to a real music performance.',
    hasSinger: true,
    framingGroup: 'singer',
    compatiblePerformances: [
      'singing-mic',
      'singing-no-mic',
      'standing-singing',
      'seated-singing',
      'natural',
    ],
  },
  {
    id: 'singer-acoustic',
    category: 'image-subject',
    label: 'Cantor + violão',
    text: 'The singer from the reference image performs naturally while holding and playing an acoustic guitar. The guitar position, the hands and the playing posture are anatomically realistic, with the left hand correctly placed on the fretboard and the right arm in a natural strumming position.',
    hasSinger: true,
    framingGroup: 'singer',
    compatiblePerformances: [
      'acoustic-singing',
      'singing-no-mic',
      'standing-singing',
      'seated-singing',
      'natural',
    ],
  },
  {
    id: 'singer-electric',
    category: 'image-subject',
    label: 'Cantor + guitarra',
    text: 'The singer from the reference image performs naturally while holding and playing an electric guitar. The guitar body and neck are correctly proportioned, the hands are anatomically correct on the fretboard and strings, and the stance is grounded and realistic.',
    hasSinger: true,
    framingGroup: 'singer',
    compatiblePerformances: [
      'electric-singing',
      'singing-no-mic',
      'standing-singing',
      'natural',
    ],
  },
  {
    id: 'singer-full-band',
    category: 'image-subject',
    label: 'Cantor + banda completa',
    text: 'The singer from the reference image remains the primary subject in the foreground while the full band performs naturally behind and around the singer, distributed across the stage. No musician blocks or overlaps the face of the singer, who stays visually dominant in the composition.',
    hasSinger: true,
    framingGroup: 'band',
    compatiblePerformances: ['natural-with-band', 'singing-mic', 'chorus-moment', 'natural'],
  },
  {
    id: 'singer-guitarist',
    category: 'image-subject',
    label: 'Cantor + guitarrista',
    text: 'The singer from the reference image is the primary subject in the foreground, with the guitarist performing naturally beside or slightly behind. The guitarist never blocks the face of the singer, and both keep realistic performance posture.',
    hasSinger: true,
    framingGroup: 'band',
    compatiblePerformances: ['natural-with-band', 'singing-mic', 'natural'],
  },
  {
    id: 'singer-drummer',
    category: 'image-subject',
    label: 'Cantor + baterista',
    text: 'The singer from the reference image is the primary subject in the foreground, with the drummer performing behind the drum kit further back in the frame. The kit and the drummer stay clearly readable without competing with the singer.',
    hasSinger: true,
    framingGroup: 'band',
    compatiblePerformances: ['natural-with-band', 'singing-mic', 'natural'],
  },
  {
    id: 'singer-guitarist-drummer',
    category: 'image-subject',
    label: 'Cantor + guitarrista + baterista',
    text: 'The singer from the reference image is the primary subject in the foreground, with the guitarist to the side and the drummer behind the kit further back, arranged in a natural stage layout. Exactly three musicians are present and nobody blocks the face of the singer.',
    hasSinger: true,
    framingGroup: 'band',
    compatiblePerformances: ['natural-with-band', 'chorus-moment', 'natural'],
  },
  {
    id: 'guitarist-solo',
    category: 'image-subject',
    label: 'Guitarrista sozinho',
    text: 'The guitarist from the reference image is alone in the frame, playing the guitar with anatomically correct hand placement on the fretboard and strings. The guitarist is not singing and no microphone is added unless it already exists in the reference image.',
    hasSinger: false,
    framingGroup: 'guitarist',
    compatiblePerformances: ['guitar-playing', 'intense-controlled', 'natural'],
  },
  {
    id: 'drummer-solo',
    category: 'image-subject',
    label: 'Baterista sozinho',
    text: 'The drummer from the reference image is alone in the frame, seated behind the drum kit and playing naturally. The posture is realistic, the sticks are correctly held in both hands and the kit is coherent, with the correct number of drums and cymbals.',
    hasSinger: false,
    framingGroup: 'drummer',
    compatiblePerformances: ['drums-playing', 'impact-moment', 'natural'],
  },
  {
    id: 'guitarist-drummer',
    category: 'image-subject',
    label: 'Guitarrista + baterista',
    text: 'The guitarist and the drummer from the reference image perform together in a natural stage composition, with the guitarist in the foreground and the drummer behind the kit. Exactly two musicians are present, with no singer and no additional musicians.',
    hasSinger: false,
    framingGroup: 'band',
    compatiblePerformances: ['band-playing', 'intense-controlled', 'natural'],
  },
  {
    id: 'band-no-singer',
    category: 'image-subject',
    label: 'Banda completa sem cantor',
    text: 'Only the instrumental members of the band from the reference image appear, performing together in a natural stage arrangement. No vocalist is created and no frontman is added: the number of musicians and their appearance follow the reference image.',
    hasSinger: false,
    framingGroup: 'band',
    compatiblePerformances: ['band-playing', 'chorus-moment', 'natural'],
  },
  {
    id: 'band-with-singer',
    category: 'image-subject',
    label: 'Banda completa com cantor',
    text: 'The full band from the reference image performs together with the singer, arranged naturally across the stage as an ensemble. The singer is clearly readable in the composition and no musician blocks the face of the singer.',
    hasSinger: true,
    framingGroup: 'band',
    compatiblePerformances: ['band-playing', 'natural-with-band', 'chorus-moment', 'natural'],
  },
]

export const IMAGE_PERFORMANCES: ImagePerformancePreset[] = [
  {
    id: 'singing-mic',
    category: 'image-performance',
    label: 'Cantando no microfone',
    text: 'The singer is singing into the microphone, holding it naturally with a believable grip, with the microphone positioned just below the mouth so it never covers the lips.',
  },
  {
    id: 'singing-no-mic',
    category: 'image-performance',
    label: 'Cantando sem segurar microfone',
    text: 'The singer is singing with both hands free, with nothing in front of the face and an open, natural upper-body posture.',
  },
  {
    id: 'acoustic-singing',
    category: 'image-performance',
    label: 'Tocando violão e cantando',
    text: 'The singer performs while playing the acoustic guitar and singing at the same time, with realistic chord-shape hand placement and a natural strumming arm position.',
  },
  {
    id: 'electric-singing',
    category: 'image-performance',
    label: 'Tocando guitarra e cantando',
    text: 'The singer performs while playing the electric guitar and singing at the same time, with credible fretting and picking hand positions and a grounded stance.',
  },
  {
    id: 'natural-with-band',
    category: 'image-performance',
    label: 'Performance natural com banda',
    text: 'A natural ensemble performance moment, with each musician engaged in playing and the overall body language authentic rather than posed.',
  },
  {
    id: 'seated-singing',
    category: 'image-performance',
    label: 'Sentado cantando',
    text: 'The singer performs seated, with a comfortable and stable posture, grounded contact with the seat and a relaxed upper body.',
  },
  {
    id: 'standing-singing',
    category: 'image-performance',
    label: 'Em pé cantando',
    text: 'The singer performs standing, with confident weight distribution and natural, believable stage presence.',
  },
  {
    id: 'guitar-playing',
    category: 'image-performance',
    label: 'Tocando guitarra',
    text: 'The guitarist is actively playing, with correct left-hand fretting, a natural picking hand position and focused attention on the performance.',
  },
  {
    id: 'intense-controlled',
    category: 'image-performance',
    label: 'Performance intensa controlada',
    text: 'An intense but controlled performance moment, with committed body language and concentrated expression, without exaggerated or theatrical distortion.',
  },
  {
    id: 'drums-playing',
    category: 'image-performance',
    label: 'Tocando bateria',
    text: 'The drummer is actively playing, with the sticks correctly held, arms in a realistic striking position and coherent limb coordination across the kit.',
  },
  {
    id: 'impact-moment',
    category: 'image-performance',
    label: 'Momento de impacto',
    text: 'A peak impact moment of the performance, with the sticks meeting a drum or cymbal and the body committed to the hit, while remaining anatomically plausible.',
  },
  {
    id: 'band-playing',
    category: 'image-performance',
    label: 'Banda tocando',
    text: 'The band is playing together, each musician engaged with their own instrument in a coherent, believable ensemble moment.',
  },
  {
    id: 'chorus-moment',
    category: 'image-performance',
    label: 'Refrão / momento forte',
    text: 'The strongest moment of the song, with heightened energy in the body language of everyone in frame, still natural and free of exaggerated poses.',
  },
  {
    id: 'natural',
    category: 'image-performance',
    label: 'Performance natural',
    text: 'A natural, unforced performance moment with authentic presence and no theatrical or exaggerated gestures.',
  },
]

function framing(
  draft: Omit<ImageFramingPreset, 'category'>,
): ImageFramingPreset {
  return { category: 'image-framing', ...draft }
}

export const IMAGE_FRAMINGS: ImageFramingPreset[] = [
  framing({
    id: 'tight-cu-front',
    label: 'Tight close-up frontal',
    text: 'Very tight frontal close-up: the face fills the frame from forehead to chin, with the eyes and mouth sharp, fully visible and unobstructed.',
    groups: ['singer'],
    lipSyncSafe: true,
    distance: 'tight-close',
    direction: 'front',
    height: 'eye',
    composition: 'portrait',
    priority: 96,
  }),
  framing({
    id: 'close-up-front',
    label: 'Close-up frontal',
    text: 'Frontal close-up on the face and the top of the shoulders, with the eyes and mouth sharp and clearly readable.',
    groups: ['singer'],
    lipSyncSafe: true,
    distance: 'close-up',
    direction: 'front',
    height: 'eye',
    composition: 'centered',
    priority: 95,
  }),
  framing({
    id: 'mcu-front',
    label: 'Medium close-up frontal',
    text: 'Frontal medium close-up from the chest up, keeping the whole face clearly visible and the expression readable.',
    groups: ['singer', 'guitarist', 'drummer', 'band'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'eye',
    composition: 'centered',
    priority: 94,
  }),
  framing({
    id: 'medium-front',
    label: 'Medium shot frontal',
    text: 'Frontal medium shot from the waist up, showing the performance gestures while keeping the face clearly visible.',
    groups: ['singer', 'guitarist', 'drummer', 'band'],
    lipSyncSafe: true,
    distance: 'medium',
    direction: 'front',
    height: 'eye',
    composition: 'centered',
    priority: 80,
  }),
  framing({
    id: 'tight-cu-tq-left',
    label: 'Tight close-up 3/4 esquerdo',
    text: 'Very tight three-quarter close-up from the left, with the face filling the frame and both eyes plus the mouth fully visible.',
    groups: ['singer'],
    lipSyncSafe: true,
    distance: 'tight-close',
    direction: 'tq-left',
    height: 'eye',
    composition: 'portrait',
    priority: 92,
  }),
  framing({
    id: 'tight-cu-tq-right',
    label: 'Tight close-up 3/4 direito',
    text: 'Very tight three-quarter close-up from the right, with the face filling the frame and both eyes plus the mouth fully visible.',
    groups: ['singer'],
    lipSyncSafe: true,
    distance: 'tight-close',
    direction: 'tq-right',
    height: 'eye',
    composition: 'portrait',
    priority: 92,
  }),
  framing({
    id: 'close-up-tq-left',
    label: 'Close-up 3/4 esquerdo',
    text: 'Close-up from the left three-quarter angle, with the face filling most of the frame and the mouth clearly visible.',
    groups: ['singer'],
    lipSyncSafe: true,
    distance: 'close-up',
    direction: 'tq-left',
    height: 'eye',
    composition: 'portrait',
    priority: 90,
  }),
  framing({
    id: 'close-up-tq-right',
    label: 'Close-up 3/4 direito',
    text: 'Close-up from the right three-quarter angle, with the face filling most of the frame and the mouth clearly visible.',
    groups: ['singer'],
    lipSyncSafe: true,
    distance: 'close-up',
    direction: 'tq-right',
    height: 'eye',
    composition: 'portrait',
    priority: 90,
  }),
  framing({
    id: 'mcu-tq-left',
    label: 'Medium close-up 3/4 esquerdo',
    text: 'Medium close-up three-quarter view from the left, keeping the face, mouth, upper body and a clear portion of the torso or instrument visible.',
    groups: ['singer', 'guitarist'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'tq-left',
    height: 'eye',
    composition: 'centered',
    priority: 88,
  }),
  framing({
    id: 'mcu-tq-right',
    label: 'Medium close-up 3/4 direito',
    text: 'Medium close-up three-quarter view from the right, keeping the face, mouth, upper body and a clear portion of the torso or instrument visible.',
    groups: ['singer', 'guitarist'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'tq-right',
    height: 'eye',
    composition: 'centered',
    priority: 88,
  }),
  framing({
    id: 'tq-left',
    label: 'Medium shot 3/4 esquerdo',
    text: 'Medium shot from the left three-quarter side, waist up, with both eyes and the mouth visible and the upper body well composed.',
    groups: ['singer', 'guitarist', 'drummer', 'band'],
    lipSyncSafe: true,
    distance: 'medium',
    direction: 'tq-left',
    height: 'eye',
    composition: 'centered',
    priority: 78,
  }),
  framing({
    id: 'tq-right',
    label: 'Medium shot 3/4 direito',
    text: 'Medium shot from the right three-quarter side, waist up, with both eyes and the mouth visible and the upper body well composed.',
    groups: ['singer', 'guitarist', 'drummer', 'band'],
    lipSyncSafe: true,
    distance: 'medium',
    direction: 'tq-right',
    height: 'eye',
    composition: 'centered',
    priority: 78,
  }),
  framing({
    id: 'eye-level-front',
    label: 'Eye-level frontal',
    text: 'Frontal portrait at exact eye level, aligned with the gaze, with a calm and natural perspective and the face fully readable.',
    groups: ['singer'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'eye',
    composition: 'portrait',
    priority: 86,
  }),
  framing({
    id: 'low-angle-slight',
    label: 'Low-angle frontal leve',
    text: 'Slightly low frontal position, just below eye level, adding presence without distorting the face or the proportions.',
    groups: ['singer', 'guitarist', 'drummer'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'low',
    composition: 'hero',
    priority: 84,
  }),
  framing({
    id: 'low-tq-left',
    label: 'Low-angle 3/4 esquerdo',
    text: 'Slightly low three-quarter view from the left, giving a subtle hero presence while keeping the face and mouth clearly readable.',
    groups: ['singer', 'guitarist'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'tq-left',
    height: 'low',
    composition: 'hero',
    priority: 82,
  }),
  framing({
    id: 'low-tq-right',
    label: 'Low-angle 3/4 direito',
    text: 'Slightly low three-quarter view from the right, giving a subtle hero presence while keeping the face and mouth clearly readable.',
    groups: ['singer', 'guitarist'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'tq-right',
    height: 'low',
    composition: 'hero',
    priority: 82,
  }),
  framing({
    id: 'high-front',
    label: 'Slight high-angle frontal',
    text: 'Slightly high frontal position, just above eye level, looking gently down at the face without hiding the mouth or flattening the features.',
    groups: ['singer'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'high',
    composition: 'portrait',
    priority: 76,
  }),
  framing({
    id: 'centered-portrait',
    label: 'Retrato simétrico centralizado',
    text: 'Centered symmetrical portrait: the face sits on the vertical midline, balanced on both sides, with even headroom and a clean performance look.',
    groups: ['singer'],
    lipSyncSafe: true,
    distance: 'close-up',
    direction: 'front',
    height: 'eye',
    composition: 'portrait',
    priority: 85,
  }),
  framing({
    id: 'off-center-cinematic',
    label: 'Off-center cinematográfico',
    text: 'Off-center cinematic framing: the subject occupies one third of the frame with deliberate negative space on the other side, still keeping the face large and readable.',
    groups: ['singer', 'guitarist', 'band'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'eye',
    composition: 'off-center',
    priority: 83,
  }),
  framing({
    id: 'over-mic-front',
    label: 'Over-microphone frontal',
    text: 'Frontal framing just above the microphone, with the mic sitting clearly below the lips and never covering the mouth. The face stays dominant in the frame.',
    groups: ['singer'],
    lipSyncSafe: true,
    distance: 'close-up',
    direction: 'front',
    height: 'eye',
    composition: 'over-mic',
    priority: 87,
    compatiblePerformances: ['singing-mic', 'standing-singing', 'natural-with-band', 'chorus-moment', 'natural'],
  }),
  framing({
    id: 'over-mic-tq',
    label: 'Over-microphone 3/4',
    text: 'Three-quarter framing from the left, just above the microphone, with the mic visible below the mouth and the face remaining fully unobstructed.',
    groups: ['singer'],
    lipSyncSafe: true,
    distance: 'close-up',
    direction: 'tq-left',
    height: 'eye',
    composition: 'over-mic',
    priority: 81,
    compatiblePerformances: ['singing-mic', 'standing-singing', 'natural-with-band', 'chorus-moment', 'natural'],
  }),
  framing({
    id: 'mcu-instrument',
    label: 'MCU com instrumento visível',
    text: 'Medium close-up that keeps the face, the upper body and a clear portion of the instrument visible in the same composition, with the mouth still fully readable.',
    groups: ['singer', 'guitarist'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'eye',
    composition: 'instrument',
    priority: 89,
  }),
  framing({
    id: 'face-instrument-edge',
    label: 'Rosto dominante + borda do instrumento',
    text: 'Face-dominant portrait with only the upper edge of the instrument entering the bottom of the frame, so the mouth stays fully visible.',
    groups: ['singer', 'guitarist'],
    lipSyncSafe: true,
    distance: 'close-up',
    direction: 'front',
    height: 'eye',
    composition: 'instrument',
    priority: 84,
  }),
  framing({
    id: 'tq-left-neck',
    label: '3/4 esquerdo com braço do instrumento',
    text: 'Three-quarter view from the left that includes the neck of the guitar running across the frame, with the fretting hand readable and the face still dominant.',
    groups: ['singer', 'guitarist'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'tq-left',
    height: 'eye',
    composition: 'instrument',
    priority: 83,
  }),
  framing({
    id: 'tq-right-picking',
    label: '3/4 direito com mão de palheta',
    text: 'Three-quarter view from the right that shows the picking or strumming hand in a natural playing position, with the face and mouth remaining clearly visible.',
    groups: ['singer', 'guitarist'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'tq-right',
    height: 'eye',
    composition: 'instrument',
    priority: 83,
  }),
  framing({
    id: 'chest-up-mic-instrument',
    label: 'Chest-up com microfone e instrumento',
    text: 'Chest-up frontal performance framing that includes the microphone below the mouth and a readable portion of the instrument, without covering the face.',
    groups: ['singer'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'eye',
    composition: 'over-mic',
    priority: 80,
    compatiblePerformances: ['singing-mic', 'acoustic-singing', 'electric-singing', 'standing-singing'],
  }),
  framing({
    id: 'low-instrument',
    label: 'Low-angle com instrumento',
    text: 'Slightly low framing that includes the instrument in the lower part of the frame while the face stays large, well lit and unobstructed.',
    groups: ['singer', 'guitarist'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'low',
    composition: 'instrument',
    priority: 77,
  }),
  framing({
    id: 'off-center-guitar',
    label: 'Off-center com instrumento',
    text: 'Off-center cinematic framing with negative space on one side and the instrument occupying the other, while the face remains the visual anchor.',
    groups: ['singer', 'guitarist'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'tq-left',
    height: 'eye',
    composition: 'off-center',
    priority: 75,
  }),
  framing({
    id: 'medium-full-instrument',
    label: 'Medium shot com instrumento inteiro',
    text: 'Medium shot wide enough to show the whole instrument, from body to headstock, together with a clearly readable face.',
    groups: ['singer', 'guitarist'],
    lipSyncSafe: true,
    distance: 'medium',
    direction: 'front',
    height: 'eye',
    composition: 'instrument',
    priority: 72,
  }),
  framing({
    id: 'portrait-fretboard',
    label: 'Retrato com braço do instrumento',
    text: 'Portrait framing that keeps the face dominant and includes a readable stretch of the fretboard along the edge of the frame.',
    groups: ['singer', 'guitarist'],
    lipSyncSafe: true,
    distance: 'close-up',
    direction: 'tq-left',
    height: 'eye',
    composition: 'instrument',
    priority: 79,
  }),
  framing({
    id: 'front-full-guitar',
    label: 'Frontal com guitarra inteira',
    text: 'Frontal framing wide enough to show the entire guitar, from the headstock to the body, together with the musician.',
    groups: ['guitarist'],
    lipSyncSafe: false,
    distance: 'medium',
    direction: 'front',
    height: 'eye',
    composition: 'instrument',
    priority: 70,
    purposes: ['scene'],
  }),
  framing({
    id: 'close-player-instrument',
    label: 'Close no músico + instrumento',
    text: 'Tight framing on the hands and the instrument, with the face of the musician still partially present in the composition.',
    groups: ['guitarist'],
    lipSyncSafe: false,
    distance: 'close-up',
    direction: 'front',
    height: 'eye',
    composition: 'instrument',
    priority: 60,
    purposes: ['scene'],
  }),
  framing({
    id: 'guitar-low-hero',
    label: 'Low-angle hero (guitarrista)',
    text: 'Slightly low hero framing of the guitarist, with the guitar body rising into the frame and a confident, grounded stance.',
    groups: ['guitarist'],
    lipSyncSafe: false,
    distance: 'medium',
    direction: 'front',
    height: 'low',
    composition: 'hero',
    priority: 74,
  }),
  framing({
    id: 'guitar-upper-body',
    label: 'Upper body + guitarra',
    text: 'Upper-body framing of the guitarist with the guitar held naturally, showing shoulders, hands and a clear stretch of the instrument.',
    groups: ['guitarist'],
    lipSyncSafe: false,
    distance: 'mcu',
    direction: 'front',
    height: 'eye',
    composition: 'instrument',
    priority: 73,
  }),
  framing({
    id: 'guitar-fretboard',
    label: 'Enquadramento com braço da guitarra',
    text: 'Framing that includes a long, readable stretch of the fretboard and the fretting hand, with the guitarist still present in the composition.',
    groups: ['guitarist'],
    lipSyncSafe: false,
    distance: 'mcu',
    direction: 'tq-left',
    height: 'high',
    composition: 'instrument',
    priority: 87,
  }),
  framing({
    id: 'guitar-picking',
    label: 'Mão de palheta visível',
    text: 'Composition that clearly shows the picking hand in a natural playing position over the strings, with the guitar body and the guitarist readable.',
    groups: ['guitarist'],
    lipSyncSafe: false,
    distance: 'mcu',
    direction: 'tq-right',
    height: 'low',
    composition: 'instrument',
    priority: 87,
  }),
  framing({
    id: 'guitar-body',
    label: 'Corpo da guitarra dominante',
    text: 'Guitar-body dominant composition: the instrument occupies a large part of the frame, with the guitarist still clearly identified behind it.',
    groups: ['guitarist'],
    lipSyncSafe: false,
    distance: 'close-up',
    direction: 'front',
    height: 'low',
    composition: 'instrument',
    priority: 62,
    purposes: ['scene'],
  }),
  framing({
    id: 'guitar-neck-full',
    label: 'Pescoço da guitarra inteiro',
    text: 'Upper-body portrait with the full guitar neck visible from body to headstock, in a natural playing angle.',
    groups: ['guitarist'],
    lipSyncSafe: false,
    distance: 'medium',
    direction: 'tq-left',
    height: 'eye',
    composition: 'instrument',
    priority: 68,
    purposes: ['scene'],
  }),
  framing({
    id: 'guitar-diagonal',
    label: 'Composição diagonal (guitarrista)',
    text: 'Dynamic diagonal composition, with the guitar neck cutting across the frame and the guitarist placed along a receding line.',
    groups: ['guitarist'],
    lipSyncSafe: false,
    distance: 'medium',
    direction: 'tq-right',
    height: 'eye',
    composition: 'diagonal',
    priority: 66,
    purposes: ['scene'],
  }),
  framing({
    id: 'guitar-slight-wide',
    label: 'Medium shot um pouco aberto',
    text: 'Slightly wide medium shot of the guitarist that still keeps the musician large in the frame and shows full playing posture.',
    groups: ['guitarist'],
    lipSyncSafe: false,
    distance: 'medium-wide',
    direction: 'front',
    height: 'eye',
    composition: 'centered',
    priority: 64,
    purposes: ['scene'],
  }),
  framing({
    id: 'guitar-off-center',
    label: 'Off-center (guitarrista)',
    text: 'Off-center cinematic framing of the guitarist, with negative space on one side and the instrument balancing the other.',
    groups: ['guitarist'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'eye',
    composition: 'off-center',
    priority: 69,
  }),
  framing({
    id: 'guitar-stage-mcu',
    label: 'MCU de palco (guitarrista)',
    text: 'Stage-performance medium close-up of the guitarist, with authentic concert presence and the guitar clearly in play.',
    groups: ['guitarist'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'eye',
    composition: 'hero',
    priority: 72,
  }),
  framing({
    id: 'guitar-face-headstock',
    label: 'Rosto + headstock',
    text: 'Close framing that keeps the face of the guitarist and the headstock of the guitar both visible in the same composition.',
    groups: ['guitarist'],
    lipSyncSafe: false,
    distance: 'close-up',
    direction: 'tq-right',
    height: 'eye',
    composition: 'instrument',
    priority: 67,
    purposes: ['scene'],
  }),
  framing({
    id: 'drums-front',
    label: 'Frontal na bateria',
    text: 'Frontal medium shot from the front of the drum kit, with the drummer clearly visible above and behind the drums.',
    groups: ['drummer'],
    lipSyncSafe: true,
    distance: 'medium',
    direction: 'front',
    height: 'eye',
    composition: 'kit',
    priority: 90,
  }),
  framing({
    id: 'drums-tq-left',
    label: '3/4 esquerdo (bateria)',
    text: 'Three-quarter framing from the left of the kit, showing the drummer, the snare and a readable stretch of the cymbals.',
    groups: ['drummer'],
    lipSyncSafe: true,
    distance: 'medium',
    direction: 'tq-left',
    height: 'eye',
    composition: 'kit',
    priority: 84,
  }),
  framing({
    id: 'drums-tq-right',
    label: '3/4 direito (bateria)',
    text: 'Three-quarter framing from the right of the kit, showing the drummer, the hi-hat side and a coherent layout of the drums.',
    groups: ['drummer'],
    lipSyncSafe: true,
    distance: 'medium',
    direction: 'tq-right',
    height: 'eye',
    composition: 'kit',
    priority: 84,
  }),
  framing({
    id: 'medium-wide',
    label: 'Medium-wide controlado',
    text: 'Controlled medium-wide framing that shows the full setup and the body language, without letting the subject become small in the frame.',
    groups: ['drummer', 'band'],
    lipSyncSafe: false,
    distance: 'medium-wide',
    direction: 'front',
    height: 'eye',
    composition: 'centered',
    priority: 70,
    purposes: ['scene'],
  }),
  framing({
    id: 'drums-chest-up',
    label: 'Chest-up atrás da caixa',
    text: 'Chest-up framing of the drummer behind the snare and the cymbals, with the face readable above the metalware.',
    groups: ['drummer'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'eye',
    composition: 'portrait',
    priority: 82,
  }),
  framing({
    id: 'drums-low',
    label: 'Low-angle (bateria)',
    text: 'Slightly low performance framing looking up at the drummer over the kit, adding presence without hiding the face.',
    groups: ['drummer'],
    lipSyncSafe: true,
    distance: 'medium',
    direction: 'front',
    height: 'low',
    composition: 'hero',
    priority: 76,
  }),
  framing({
    id: 'drums-eye-portrait',
    label: 'Retrato eye-level na bateria',
    text: 'Eye-level drummer portrait at the kit, with the snare in the lower frame and the face well lit and unobstructed.',
    groups: ['drummer'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'eye',
    composition: 'centered',
    priority: 80,
  }),
  framing({
    id: 'drums-over-tom',
    label: 'Perspectiva sobre o tom',
    text: 'Over-tom perspective: the rack tom sits in the foreground while the drummer remains clearly readable behind the kit.',
    groups: ['drummer'],
    lipSyncSafe: false,
    distance: 'mcu',
    direction: 'front',
    height: 'high',
    composition: 'kit',
    priority: 64,
    purposes: ['scene'],
  }),
  framing({
    id: 'drums-cymbal',
    label: 'Composição com prato em quadro',
    text: 'Cymbal-framed composition: a cymbal occupies one edge of the frame and the drummer plays behind it, still clearly identified.',
    groups: ['drummer'],
    lipSyncSafe: false,
    distance: 'mcu',
    direction: 'tq-left',
    height: 'low',
    composition: 'kit',
    priority: 63,
    purposes: ['scene'],
  }),
  framing({
    id: 'drums-kick-snare',
    label: 'Bumbo, caixa e chimbal legíveis',
    text: 'Composition where the kick, the snare and the hi-hat are all readable together, with the drummer in a natural playing posture.',
    groups: ['drummer'],
    lipSyncSafe: false,
    distance: 'medium-wide',
    direction: 'tq-right',
    height: 'eye',
    composition: 'layered',
    priority: 68,
    purposes: ['scene'],
  }),
  framing({
    id: 'drums-sticks',
    label: 'Baquetas em posição natural',
    text: 'Framing that shows the sticks held naturally, one ready on the snare and the other over a cymbal or tom, with believable arm positions.',
    groups: ['drummer'],
    lipSyncSafe: false,
    distance: 'mcu',
    direction: 'tq-right',
    height: 'eye',
    composition: 'hero',
    priority: 66,
    compatiblePerformances: ['drums-playing', 'impact-moment', 'natural'],
  }),
  framing({
    id: 'drums-impact',
    label: 'Momento de impacto (enquadramento)',
    text: 'Impact-moment framing: a stick meets a drum or cymbal, with the body committed to the hit and the kit remaining anatomically coherent.',
    groups: ['drummer'],
    lipSyncSafe: false,
    distance: 'medium',
    direction: 'front',
    height: 'low',
    composition: 'hero',
    priority: 65,
    compatiblePerformances: ['impact-moment', 'drums-playing', 'chorus-moment'],
    purposes: ['scene'],
  }),
  framing({
    id: 'drums-off-center',
    label: 'Off-center (bateria)',
    text: 'Off-center cinematic drum composition, with the drummer on one third of the frame and the kit creating depth on the other side.',
    groups: ['drummer'],
    lipSyncSafe: true,
    distance: 'medium',
    direction: 'front',
    height: 'eye',
    composition: 'off-center',
    priority: 72,
  }),
  framing({
    id: 'drums-stage-medium',
    label: 'Medium shot de palco (bateria)',
    text: 'Stage-performance medium shot of the drummer, showing enough of the kit and the body language for a live concert still.',
    groups: ['drummer'],
    lipSyncSafe: false,
    distance: 'medium-wide',
    direction: 'tq-left',
    height: 'eye',
    composition: 'centered',
    priority: 67,
    purposes: ['scene'],
  }),
  framing({
    id: 'drums-portrait-depth',
    label: 'Retrato com profundidade do kit',
    text: 'Drummer portrait with kit depth layers: snare close, toms receding, cymbals in the background, all coherent and uncluttered.',
    groups: ['drummer'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'tq-left',
    height: 'eye',
    composition: 'layered',
    priority: 74,
  }),
  framing({
    id: 'singer-foreground',
    label: 'Cantor em primeiro plano',
    text: 'The singer is framed large in the foreground with the rest of the band visible but secondary behind, in shallower focus.',
    groups: ['band'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'eye',
    composition: 'band-context',
    priority: 94,
  }),
  framing({
    id: 'band-behind',
    label: 'Banda distribuída atrás',
    text: 'The band is distributed naturally across the background of the stage, evenly spaced, with clear separation between the musicians.',
    groups: ['band'],
    lipSyncSafe: true,
    distance: 'medium',
    direction: 'front',
    height: 'eye',
    composition: 'layered',
    priority: 82,
  }),
  framing({
    id: 'stage-diagonal',
    label: 'Composição diagonal de palco',
    text: 'Diagonal stage composition, with the performers arranged along a receding line that gives depth to the frame.',
    groups: ['band'],
    lipSyncSafe: false,
    distance: 'medium-wide',
    direction: 'tq-left',
    height: 'eye',
    composition: 'diagonal',
    priority: 68,
    purposes: ['scene'],
  }),
  framing({
    id: 'mcu-front-band-soft',
    label: 'MCU frontal com banda suave atrás',
    text: 'Frontal medium close-up of the singer, with the band softly visible and slightly defocused behind, never covering the face.',
    groups: ['band'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'eye',
    composition: 'portrait',
    priority: 92,
  }),
  framing({
    id: 'tq-singer-band',
    label: '3/4 do cantor com banda ao fundo',
    text: 'Three-quarter singer-foreground framing, with the band distributed in the background and the mouth of the singer fully visible.',
    groups: ['band'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'tq-left',
    height: 'eye',
    composition: 'band-context',
    priority: 88,
  }),
  framing({
    id: 'centered-portrait-band',
    label: 'Retrato centralizado com banda',
    text: 'Centered singer portrait with the drummer and the guitarist readable behind, kept secondary and out of the face of the singer.',
    groups: ['band'],
    lipSyncSafe: true,
    distance: 'close-up',
    direction: 'front',
    height: 'eye',
    composition: 'portrait',
    priority: 86,
  }),
  framing({
    id: 'low-hero-band',
    label: 'Low-angle hero com banda',
    text: 'Slightly low singer-hero framing, with the band standing behind and below the visual weight of the singer.',
    groups: ['band'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'front',
    height: 'low',
    composition: 'hero',
    priority: 84,
  }),
  framing({
    id: 'medium-context-band',
    label: 'Medium shot com contexto da banda',
    text: 'Medium shot of the singer with full performance context: band, instruments and stage readable, while the singer stays the largest subject.',
    groups: ['band'],
    lipSyncSafe: true,
    distance: 'medium',
    direction: 'front',
    height: 'eye',
    composition: 'band-context',
    priority: 80,
  }),
  framing({
    id: 'off-center-band-depth',
    label: 'Off-center com profundidade da banda',
    text: 'Off-center singer framing with layered band depth: one musician closer, another further back, creating a cinematic stage depth.',
    groups: ['band'],
    lipSyncSafe: true,
    distance: 'mcu',
    direction: 'tq-right',
    height: 'eye',
    composition: 'off-center',
    priority: 81,
  }),
  framing({
    id: 'band-centered',
    label: 'Banda completa centralizada',
    text: 'Centered full-band performance composition, with the musicians arranged as an ensemble and no extra vocalist added.',
    groups: ['band'],
    lipSyncSafe: false,
    distance: 'medium-wide',
    direction: 'front',
    height: 'eye',
    composition: 'centered',
    priority: 74,
    purposes: ['scene'],
  }),
  framing({
    id: 'band-guitar-fg',
    label: 'Guitarrista à frente, baterista atrás',
    text: 'Guitarist in the foreground with the drummer behind the kit in the background, in a natural two-layer stage arrangement.',
    groups: ['band'],
    lipSyncSafe: false,
    distance: 'medium',
    direction: 'tq-left',
    height: 'eye',
    composition: 'layered',
    priority: 73,
    purposes: ['scene'],
  }),
  framing({
    id: 'band-layered',
    label: 'Composição em camadas',
    text: 'Layered performance composition: distinct depth planes for each musician, with clear separation and no overlapping faces.',
    groups: ['band'],
    lipSyncSafe: false,
    distance: 'medium',
    direction: 'front',
    height: 'eye',
    composition: 'layered',
    priority: 72,
    purposes: ['scene'],
  }),
  framing({
    id: 'band-off-center',
    label: 'Off-center da banda',
    text: 'Off-center cinematic band framing, with the group occupying two thirds of the frame and deliberate negative space on the remaining side.',
    groups: ['band'],
    lipSyncSafe: false,
    distance: 'medium-wide',
    direction: 'tq-right',
    height: 'eye',
    composition: 'off-center',
    priority: 71,
    purposes: ['scene'],
  }),
  framing({
    id: 'band-instrumental-portrait',
    label: 'Retrato instrumental',
    text: 'Instrumental performance portrait of the band, focused on the musicians and their instruments, with no singer invented in the frame.',
    groups: ['band'],
    lipSyncSafe: false,
    distance: 'medium',
    direction: 'front',
    height: 'eye',
    composition: 'portrait',
    priority: 70,
    purposes: ['scene'],
  }),
  framing({
    id: 'band-live-stage',
    label: 'Estilo palco ao vivo',
    text: 'Live-stage style composition of the band, with concert lighting from the reference, authentic spacing and a professional still-frame look.',
    groups: ['band'],
    lipSyncSafe: false,
    distance: 'medium-wide',
    direction: 'front',
    height: 'low',
    composition: 'hero',
    priority: 69,
    purposes: ['scene'],
  }),
]

/**
 * Enquadramento "Automático profissional" por grupo. A primeira opção
 * compatível vence — em Lipsync os ângulos abertos são descartados antes.
 */
export const AUTO_IMAGE_FRAMING_BY_GROUP: Record<
  'singer' | 'guitarist' | 'drummer' | 'band',
  Array<Exclude<ImageFramingId, 'auto'>>
> = {
  singer: ['mcu-front', 'close-up-front', 'mcu-tq-left', 'medium-front'],
  guitarist: ['mcu-instrument', 'mcu-front', 'medium-front', 'tq-left'],
  drummer: ['drums-front', 'medium-front', 'tq-left', 'mcu-front'],
  band: ['singer-foreground', 'medium-front', 'band-behind', 'tq-left'],
}

/**
 * Prioridade das variações quando o cantor está em foco de lipsync.
 * As primeiras são as mais úteis para boca e rosto visíveis.
 */
export const SINGER_LIPSYNC_VARIATIONS: Array<Exclude<ImageFramingId, 'auto'>> = [
  'tight-cu-front',
  'close-up-front',
  'mcu-front',
  'medium-front',
  'tight-cu-tq-left',
  'tight-cu-tq-right',
  'close-up-tq-left',
  'close-up-tq-right',
  'mcu-tq-left',
  'mcu-tq-right',
  'tq-left',
  'tq-right',
  'eye-level-front',
  'low-angle-slight',
  'low-tq-left',
  'low-tq-right',
  'high-front',
  'centered-portrait',
  'off-center-cinematic',
  'over-mic-front',
  'over-mic-tq',
  'mcu-instrument',
  'face-instrument-edge',
]

export const IMAGE_SUBJECT_BY_ID = new Map<ImageSubjectId, ImageSubjectPreset>(
  IMAGE_SUBJECTS.map((item) => [item.id, item]),
)
export const IMAGE_PERFORMANCE_BY_ID = new Map<ImagePerformanceId, ImagePerformancePreset>(
  IMAGE_PERFORMANCES.map((item) => [item.id, item]),
)
export const IMAGE_FRAMING_BY_ID = new Map<
  Exclude<ImageFramingId, 'auto'>,
  ImageFramingPreset
>(IMAGE_FRAMINGS.map((item) => [item.id, item]))
